### ISSUE TITLE
Decompiling error: Invalid chunk type

### ISSUE THREAD

**Issue by CesarTrigo** [applivery/roadmap#131]
**Describe the bug**
Some APKs are failing to decompile while using [APKTool v2.4.1](https://github.com/iBotPeaches/Apktool/releases/tag/v2.4.1) reverse engineering tool.

**Error description**
Exception in thread "main" brut.androlib.AndrolibException: Invalid chunk type: expected=0x00000200, got=0x00000203
```
➜  test java -jar apktool_2.4.1.jar -f d prod.apk  -m -s -o output/prod
I: Using Apktool 2.4.1 on prod.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Invalid chunk type: expected=0x00000200, got=0x00000203
	at brut.androlib.res.decoder.ARSCDecoder.checkChunkType(ARSCDecoder.java:542)
	at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:88)
	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:82)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:48)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:786)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:67)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:59)
	at brut.androlib.Androlib.getResTable(Androlib.java:66)
	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:236)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:118)
	at brut.apktool.Main.cmdDecode(Main.java:170)
	at brut.apktool.Main.main(Main.java:76)
```

**Actions taken**
We are contacting APKTool team to discover more about the issue. It seems to be related with a wrong parsing of packages and libraries (`0x00000200` and `0x00000203` respectively).

Related GitHub Issues:
- [#2249](https://github.com/iBotPeaches/Apktool/issues/2249) (In Progress)
- [#1990](https://github.com/iBotPeaches/Apktool/issues/1990)
- [#2099](https://github.com/iBotPeaches/Apktool/issues/2099)

**Alternatives**
We are considering migrate to [APKAnalyzer](https://developer.android.com/studio/command-line/apkanalyzer) or [aapt](https://developer.android.com/studio/command-line/aapt2).

**Comment by fluenthome** [comment]
Our app is unable to update until this is resolved. Is there any way of telling what kind of timeframe this has?

**Comment by KUUSIOSK** [comment]
Same issue here...

**Comment by CesarTrigo** [comment]
Dear @fluenthome  & @KUUSIOSK after a deeper investigation, this issue will be fixed in today's deployment since we are moving away from [APKTool](https://github.com/iBotPeaches/Apktool/releases/tag/v2.4.1) to the official Android Tool `aapt2` 

Best,
C.

**Comment by Tushar-Rastogi** [comment]
Hi @CesarTrigo any luck with it as I'm using https://github.com/levyitay/AddSecurityExceptionAndroid to add security Exception however it is using APKtool itself.
Can you suggest any work around for APK tool.

**Comment by CesarTrigo** [comment]
Hi @Tushar-Rastogi unfortunately this issue is not being resolved by the APKTool etam so we decided to move away from it in favor to the Official Android Tools (AAPT2).
Good luck!
